# Generated by Django 6.0.5 on 2026-06-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoGrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('EN CURSO', 'En Curso'), ('EN REVISION', 'En Revision'), ('CONCLUIDO', 'Concluido')], default='EN REVISION', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proyecto de Grado',
                'verbose_name_plural': 'Proyectos de Grado',
                'db_table': 'Proyecto de grado',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_version', models.IntegerField()),
                ('url_pdf', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('APROBADO', 'Aprobado'), ('EN REVISION', 'En Revision'), ('OBSERVADO', 'Observado')], default='EN REVISION', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'versiones',
                'ordering': ['-numero_version'],
            },
        ),
    ]
