# Generated by Django 6.0.5 on 2026-06-12 03:55

from django.db import migrations, models


def ensure_nombre_archivo(apps, schema_editor):
    """Crea la columna solo si no existe.

    En Supabase la columna fue creada a mano antes de esta migración; en bases
    nuevas (p.ej. la BD de tests) sí hay que crearla.
    """
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        columns = [
            col.name
            for col in connection.introspection.get_table_description(cursor, 'versiones')
        ]
    if 'nombre_archivo' in columns:
        return
    version_model = apps.get_model('projects', 'Version')
    schema_editor.add_field(
        version_model, version_model._meta.get_field('nombre_archivo')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectogrado',
            name='etapa',
            field=models.CharField(choices=[('PROPUESTA', 'Propuesta'), ('ANTEPROYECTO', 'Anteproyecto'), ('DESARROLLO', 'Desarrollo'), ('REVISION', 'Revision'), ('DEFENSA', 'Defensa')], default='PROPUESTA', max_length=20),
        ),
        # Registrar el campo en el estado de Django sin tocar el esquema...
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='version',
                    name='nombre_archivo',
                    field=models.CharField(blank=True, max_length=255),
                ),
            ],
            database_operations=[],
        ),
        # ...y crear la columna únicamente donde no exista todavía.
        migrations.RunPython(ensure_nombre_archivo, migrations.RunPython.noop),
    ]
