# Generated by Django 6.0.5 on 2026-06-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='nombre_archivo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='version',
            name='numero_version',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='version',
            name='url_pdf',
            field=models.CharField(max_length=500),
        ),
    ]
