# Generated by Django 6.0.5 on 2026-05-31 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina', models.IntegerField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('ancho', models.FloatField()),
                ('alto', models.FloatField()),
                ('comentario', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'nota comentario',
                'verbose_name_plural': 'notas comentarios',
                'db_table': 'nota_comentario',
            },
        ),
        migrations.CreateModel(
            name='ProyectoGrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('en revision', 'En revisión'), ('rechazado', 'Rechazado'), ('aprovado', 'Aprobado')], default='en revision', max_length=20)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_grado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'proyecto de grado',
                'verbose_name_plural': 'proyectos de grado',
                'db_table': 'proyecto de grado',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_version', models.IntegerField(db_column='numero de version')),
                ('url_pdf', models.FileField(upload_to='proyectos/pdfs/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisando', 'Revisando'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('observado', 'Observado')], default='pendiente', max_length=20)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='projects.proyectogrado')),
            ],
            options={
                'verbose_name': 'versión',
                'verbose_name_plural': 'versiones',
                'db_table': 'versiones',
            },
        ),
        migrations.CreateModel(
            name='Anotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto (Pendiente)'), ('resuelto', 'Resuelto (Corregido)')], default='abierto', max_length=20)),
                ('accion_correctiva', models.CharField(blank=True, max_length=255, null=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('coregido_el', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nota_correccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correccion_de', to='projects.notacomentario')),
                ('nota_observacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observacion_de', to='projects.notacomentario')),
                ('version', models.ForeignKey(db_column='version _id', on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones', to='projects.version')),
            ],
            options={
                'verbose_name': 'anotación',
                'verbose_name_plural': 'anotaciones',
                'db_table': 'anotacion',
            },
        ),
    ]
