# Generated by Django 6.0.5 on 2026-06-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('CORREGIDA', 'Corregida'), ('SIN CORREGIR', 'Sin Corregir')], default='SIN CORREGIR', max_length=20)),
                ('accion_a_realizar', models.CharField(blank=True, max_length=255)),
                ('accion_realizada', models.CharField(blank=True, max_length=255)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('corregido_el', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'anotacion',
                'ordering': ['-creado_el'],
            },
        ),
        migrations.CreateModel(
            name='NotaComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina', models.IntegerField()),
                ('x', models.DecimalField(decimal_places=2, max_digits=10)),
                ('y', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comentario', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'nota_comentario',
            },
        ),
    ]
