# Generated by Django 6.0.5 on 2026-06-07 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annotations', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anotacion',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anotacion',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones', to='projects.version'),
        ),
        migrations.AddField(
            model_name='anotacion',
            name='nota_correccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anotaciones_correccion', to='annotations.notacomentario'),
        ),
        migrations.AddField(
            model_name='anotacion',
            name='nota_observacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anotaciones_observacion', to='annotations.notacomentario'),
        ),
    ]
