# Generated by Django 6.0.5 on 2026-06-12 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anotacion',
            name='codigo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anotacion',
            name='severidad',
            field=models.CharField(choices=[('CRITICO', 'Critico'), ('SUGERENCIA', 'Sugerencia')], default='SUGERENCIA', max_length=20),
        ),
        migrations.AddField(
            model_name='anotacion',
            name='subsanada_el',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anotacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('SUBSANADA', 'Subsanada'), ('APROBADA', 'Aprobada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='notacomentario',
            name='alto',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='notacomentario',
            name='ancho',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='notacomentario',
            name='comentario',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notacomentario',
            name='x',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='notacomentario',
            name='y',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.CreateModel(
            name='AnotacionEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CREACION', 'Creacion'), ('SUBSANACION', 'Subsanacion'), ('APROBACION', 'Aprobacion'), ('REOBSERVACION', 'Reobservacion')], max_length=20)),
                ('texto', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anotacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='annotations.anotacion')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_anotacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'anotacion_evento',
                'ordering': ['created_at'],
            },
        ),
    ]
