# Generated by Django 6.0.5 on 2026-06-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='capacidades',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
