# Generated by Django 6.0.5 on 2026-06-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstudiantesMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'estudiantes_materia',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('semestre', models.IntegerField()),
                ('grupo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Materias',
                'db_table': 'materia',
            },
        ),
    ]
