# Generated by Django 6.0.5 on 2026-06-07 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantesmateria',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_inscritas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materia',
            name='docente_a_cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias_impartidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estudiantesmateria',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='academic.materia'),
        ),
        migrations.AlterUniqueTogether(
            name='estudiantesmateria',
            unique_together={('materia', 'estudiante')},
        ),
    ]
