# Generated by Django 6.0.5 on 2026-06-07 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relationships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tutortribunal',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes_tutorados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tutortribunal',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutores_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='tutortribunal',
            unique_together={('estudiante', 'docente', 'relacion')},
        ),
    ]
