# Generated by Django 6.0.5 on 2026-05-31 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publico_objetivo', models.CharField(choices=[('estudiantes', 'Estudiantes'), ('tutor', 'Tutor'), ('tribunal', 'Tribunal'), ('documento', 'Documento')], default='documento', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('version', models.IntegerField()),
                ('semestre', models.IntegerField()),
            ],
            options={
                'db_table': 'cronograma',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('semestre', models.IntegerField()),
                ('grupo', models.CharField(max_length=255)),
                ('docente_acargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_dictadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'materia',
            },
        ),
        migrations.CreateModel(
            name='TutorTribunales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacion', models.CharField(choices=[('tutor', 'Tutor'), ('tribunal', 'Tribunal')], db_column='relacion ', default='tribunal', max_length=20)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes_guiados', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentores_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tutor/tribunal',
                'verbose_name_plural': 'tutores y tribunales',
                'db_table': 'tutor_tribunales',
            },
        ),
        migrations.CreateModel(
            name='EstudiantesMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_inscritas', to=settings.AUTH_USER_MODEL)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='academics.materia')),
            ],
            options={
                'verbose_name': 'estudiante por materia',
                'verbose_name_plural': 'estudiantes por materia',
                'db_table': 'estudiantes_materia',
                'unique_together': {('materia', 'estudiante')},
            },
        ),
    ]
