# Generated by Django 6.0.5 on 2026-06-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publico_objetivo', models.CharField(choices=[('ESTUDIANTES', 'Estudiantes'), ('DOCENTES', 'Docentes')], default='ESTUDIANTES', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('semestre', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cronograma',
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
