# Generated by Django 6.0.5 on 2026-06-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronograma',
            name='tipo',
            field=models.CharField(choices=[('ENTREGA', 'Entrega'), ('REVISION', 'Revision'), ('DEFENSA', 'Defensa'), ('ADMINISTRATIVO', 'Administrativo')], default='ENTREGA', max_length=20),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='publico_objetivo',
            field=models.CharField(choices=[('ESTUDIANTES', 'Estudiantes'), ('DOCENTES', 'Docentes'), ('TODOS', 'Todos')], default='ESTUDIANTES', max_length=20),
        ),
    ]
