# Generated by Django 6.0.5 on 2026-06-12 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='categoria',
            field=models.CharField(choices=[('ENTREGA', 'Entrega'), ('OBSERVACION', 'Observacion'), ('SISTEMA', 'Sistema'), ('RECORDATORIO', 'Recordatorio')], default='SISTEMA', max_length=20),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='emisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_enviadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='titulo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
